package food_ordering_system.GUI;

import food_ordering_system.Utilities.GraphPanel;
import food_ordering_system.Utilities.LoginRedirect;

import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.util.List;

public class DeliveryRunnerDashboard extends javax.swing.JFrame {
    private String timestamp = "Days";//by default
    private GraphPanel graphPanel;

    public DeliveryRunnerDashboard(String runnerID) {
        setTitle("Runner Interface");
        initComponents();

        List<Double> revenues = new ArrayList<>();
        graphPanel = new GraphPanel(revenues, "Revenue (RM)", timestamp);
        pnlGraph.add(graphPanel);

        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        new LoginRedirect().logout(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashboard = new javax.swing.JPanel();
        pnlGraph = new javax.swing.JPanel();
        pnlButton = new javax.swing.JPanel();
        btnDays = new javax.swing.JButton();
        btnWeeks = new javax.swing.JButton();
        btnMonths = new javax.swing.JButton();
        pnlNavigator = new javax.swing.JPanel();
        lblRunnerID = new javax.swing.JLabel();
        lblRunnerName = new javax.swing.JLabel();
        btnManageTasks = new javax.swing.JButton();
        btnTaskHistory = new javax.swing.JButton();
        scrlPnlReviews = new javax.swing.JScrollPane();
        txtReviews = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlDashboard.setBackground(Color.decode("#500073"));
        pnlDashboard.setLayout(new java.awt.BorderLayout());

        pnlGraph.setBackground(Color.decode("#500073"));
        pnlGraph.setLayout(new javax.swing.BoxLayout(pnlGraph, javax.swing.BoxLayout.LINE_AXIS));
        pnlDashboard.add(pnlGraph, java.awt.BorderLayout.CENTER);

        pnlButton.setBackground(Color.decode("#500073"));

        btnDays.setText("Days");
        btnDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaysActionPerformed(evt);
            }
        });
        pnlButton.add(btnDays);

        btnWeeks.setText("Weeks");
        btnWeeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeeksActionPerformed(evt);
            }
        });
        pnlButton.add(btnWeeks);

        btnMonths.setText("Months");
        btnMonths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthsActionPerformed(evt);
            }
        });
        pnlButton.add(btnMonths);

        pnlDashboard.add(pnlButton, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlDashboard);

        pnlNavigator.setBackground(Color.decode("#500073"));
        pnlNavigator.setForeground(new java.awt.Color(255, 255, 255));
        pnlNavigator.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        lblRunnerID.setForeground(new java.awt.Color(255, 255, 255));
        lblRunnerID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRunnerID.setText("ID: <Runner ID>");
        lblRunnerID.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlNavigator.add(lblRunnerID);

        lblRunnerName.setForeground(new java.awt.Color(255, 255, 255));
        lblRunnerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRunnerName.setText("Name: <Runner Name>");
        pnlNavigator.add(lblRunnerName);

        btnManageTasks.setBackground(Color.decode("#F14A00"));
        btnManageTasks.setText("Manage Tasks");
        btnManageTasks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManageTasks.setMinimumSize(new java.awt.Dimension(140, 25));
        btnManageTasks.setPreferredSize(new java.awt.Dimension(140, 50));
        btnManageTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTasksActionPerformed(evt);
            }
        });
        pnlNavigator.add(btnManageTasks);

        btnTaskHistory.setBackground(Color.decode("#F14A00"));
        btnTaskHistory.setText("Check Task History");
        btnTaskHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaskHistory.setMinimumSize(new java.awt.Dimension(140, 25));
        btnTaskHistory.setPreferredSize(new java.awt.Dimension(140, 50));
        pnlNavigator.add(btnTaskHistory);

        getContentPane().add(pnlNavigator);

        scrlPnlReviews.setBackground(Color.decode("#500073"));
        scrlPnlReviews.setPreferredSize(new java.awt.Dimension(400, 200));

        txtReviews.setEditable(false);
        txtReviews.setColumns(20);
        txtReviews.setRows(5);
        txtReviews.setText("Customer reviews will appear here\ne.g.\nC001: Fast delivery (4.2 rating)\nC002: Wowowowow (5.0 rating)\nC003: Slow delivery (2.3 rating)");
        txtReviews.setFocusable(false);
        scrlPnlReviews.setViewportView(txtReviews);

        getContentPane().add(scrlPnlReviews);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaysActionPerformed
        graphPanel.setxAxisLabel("Days");
        graphPanel.invalidate();
        graphPanel.repaint();
    }//GEN-LAST:event_btnDaysActionPerformed

    private void btnWeeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeeksActionPerformed
        graphPanel.setxAxisLabel("Weeks");
        graphPanel.invalidate();
        graphPanel.repaint();
    }//GEN-LAST:event_btnWeeksActionPerformed

    private void btnMonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthsActionPerformed
        graphPanel.setxAxisLabel("Months");
        graphPanel.invalidate();
        graphPanel.repaint();
    }//GEN-LAST:event_btnMonthsActionPerformed

    private void btnManageTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTasksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageTasksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryRunnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryRunnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryRunnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryRunnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryRunnerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDays;
    private javax.swing.JButton btnManageTasks;
    private javax.swing.JButton btnMonths;
    private javax.swing.JButton btnTaskHistory;
    private javax.swing.JButton btnWeeks;
    private javax.swing.JLabel lblRunnerID;
    private javax.swing.JLabel lblRunnerName;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlGraph;
    private javax.swing.JPanel pnlNavigator;
    private javax.swing.JScrollPane scrlPnlReviews;
    private javax.swing.JTextArea txtReviews;
    // End of variables declaration//GEN-END:variables

}
