package food_ordering_system.GUI;

import food_ordering_system.Controller.VendorController;
import food_ordering_system.Utilities.GraphPanel;
import food_ordering_system.Utilities.LoginRedirect;

import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.util.List;

public class VendorDashboard extends javax.swing.JFrame {
    private String timestamp = "Days";//by default
    private GraphPanel graphPanel;
    private final VendorController vendorController = new VendorController();

    public VendorDashboard(String vendorID) {
        setTitle("Vendor Dashboard");
        List<Double> revenues = getRevenues(timestamp);
        graphPanel = new GraphPanel(revenues, "Revenue (RM)", timestamp);

        initComponents();
        pnlGraph.add(graphPanel);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        new LoginRedirect().logout(this);
        setVisible(true);
    }

    private List<Double> getRevenues(String timestamp){
        List<Double> revenues = new ArrayList<>();
        //will fetch data from orders.txt

        switch (timestamp){
            case "Days" -> {
                //
            }
            case "Months" -> {
                //
            }
            case "Quarters" -> {
                //
            }
        }
        revenues.add(5.0);
        revenues.add(1.0);
        revenues.add(5.0);
        revenues.add(1.0);
        return revenues;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashboard = new javax.swing.JPanel();
        pnlGraph = new javax.swing.JPanel();
        pnlButton = new javax.swing.JPanel();
        btnDays = new javax.swing.JButton();
        btnWeeks = new javax.swing.JButton();
        btnMonths = new javax.swing.JButton();
        pnlNavigator = new javax.swing.JPanel();
        lblVendorID = new javax.swing.JLabel();
        lblVendorName = new javax.swing.JLabel();
        btnManageItems = new javax.swing.JButton();
        btnManageOrders = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();
        scrlPnlReviews = new javax.swing.JScrollPane();
        txtReviews = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendor");
        setBackground(Color.decode("#500073"));
        setMinimumSize(new java.awt.Dimension(1200, 250));
        setName("vendorFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        pnlDashboard.setBackground(Color.decode("#500073"));
        pnlDashboard.setLayout(new java.awt.BorderLayout());

        pnlGraph.setBackground(Color.decode("#500073"));
        pnlGraph.setLayout(new javax.swing.BoxLayout(pnlGraph, javax.swing.BoxLayout.LINE_AXIS));
        pnlDashboard.add(pnlGraph, java.awt.BorderLayout.CENTER);

        pnlButton.setBackground(Color.decode("#500073"));

        btnDays.setText("Days");
        btnDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaysActionPerformed(evt);
            }
        });
        pnlButton.add(btnDays);

        btnWeeks.setText("Weeks");
        btnWeeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeeksActionPerformed(evt);
            }
        });
        pnlButton.add(btnWeeks);

        btnMonths.setText("Months");
        btnMonths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthsActionPerformed(evt);
            }
        });
        pnlButton.add(btnMonths);

        pnlDashboard.add(pnlButton, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlDashboard);

        pnlNavigator.setBackground(Color.decode("#500073"));
        pnlNavigator.setForeground(new java.awt.Color(255, 255, 255));
        pnlNavigator.setNextFocusableComponent(btnManageItems);
        pnlNavigator.setLayout(new java.awt.GridLayout(5, 0, 0, 5));

        lblVendorID.setForeground(new java.awt.Color(255, 255, 255));
        lblVendorID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVendorID.setText("ID: <Vendor ID>");
        lblVendorID.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlNavigator.add(lblVendorID);

        lblVendorName.setForeground(new java.awt.Color(255, 255, 255));
        lblVendorName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVendorName.setText("Name: <Vendor Name>");
        pnlNavigator.add(lblVendorName);

        btnManageItems.setBackground(Color.decode("#F14A00"));
        btnManageItems.setText("Manage Items");
        btnManageItems.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManageItems.setMinimumSize(new java.awt.Dimension(140, 25));
        btnManageItems.setPreferredSize(new java.awt.Dimension(140, 50));
        btnManageItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageItemsActionPerformed(evt);
            }
        });
        pnlNavigator.add(btnManageItems);

        btnManageOrders.setBackground(Color.decode("#F14A00"));
        btnManageOrders.setText("Manage Orders");
        btnManageOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnManageOrders.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManageOrders.setMinimumSize(new java.awt.Dimension(140, 25));
        btnManageOrders.setPreferredSize(new java.awt.Dimension(140, 50));
        pnlNavigator.add(btnManageOrders);

        btnOrderHistory.setBackground(Color.decode("#F14A00"));
        btnOrderHistory.setText("Check Order History");
        btnOrderHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrderHistory.setMinimumSize(new java.awt.Dimension(140, 25));
        btnOrderHistory.setPreferredSize(new java.awt.Dimension(140, 50));
        pnlNavigator.add(btnOrderHistory);

        getContentPane().add(pnlNavigator);

        scrlPnlReviews.setBackground(Color.decode("#500073"));
        scrlPnlReviews.setPreferredSize(new java.awt.Dimension(400, 200));

        txtReviews.setEditable(false);
        txtReviews.setColumns(20);
        txtReviews.setRows(5);
        txtReviews.setText("Customer reviews will appear here\ne.g.\nC001: Good Food (4.2 rating)\nC002: Yummers (5.0 rating)\nC003: Food too salty (2.3 rating)");
        txtReviews.setFocusable(false);
        scrlPnlReviews.setViewportView(txtReviews);

        getContentPane().add(scrlPnlReviews);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageItemsActionPerformed

    private void btnDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaysActionPerformed
        graphPanel.setxAxisLabel("Days");
        graphPanel.invalidate();
        graphPanel.repaint();
    }//GEN-LAST:event_btnDaysActionPerformed

    private void btnWeeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeeksActionPerformed
        graphPanel.setxAxisLabel("Weeks");
        graphPanel.invalidate();
        graphPanel.repaint();
    }//GEN-LAST:event_btnWeeksActionPerformed

    private void btnMonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthsActionPerformed
        graphPanel.setxAxisLabel("Months");
        graphPanel.invalidate();
        graphPanel.repaint();
    }//GEN-LAST:event_btnMonthsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDays;
    private javax.swing.JButton btnManageItems;
    private javax.swing.JButton btnManageOrders;
    private javax.swing.JButton btnMonths;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JButton btnWeeks;
    private javax.swing.JLabel lblVendorID;
    private javax.swing.JLabel lblVendorName;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlGraph;
    private javax.swing.JPanel pnlNavigator;
    private javax.swing.JScrollPane scrlPnlReviews;
    private javax.swing.JTextArea txtReviews;
    // End of variables declaration//GEN-END:variables
}
